### ISSUE TITLE
Broken GPU Acceleration

### ISSUE THREAD

**Issue by ducks-c** [Krissh-C/X1C2-macOS#11]
macOS Ventura dropped support for 4th Gen HD Graphics.
When using [Opencore Legacy Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher), it may bring up the prompt to install patches directly. In the case that it doesn't or if the app isn't installed, please look below:

3. Download the latest version of [Opencore Legacy Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher) if you haven't already
4. Open the app and select "Post-Install Root Patch"
5. It should bring up a menu with Graphics: Haswell
6. Select Install Root patches
7. Select Yes to relaunch as Root
8. Enter your password
9. Reboot after patches have been installed

**Comment by Bable10** [comment]
hi, always me, is there a method to make work gpu acceleration on sonoma?

**Comment by ducks-c** [comment]
The steps mentioned above work for macOS Ventura and up which includes Sonoma

**Comment by Bable10** [comment]
ok but when i click on post-install root patches it says that no patches are required and also i can't turn down the resolution

**Comment by ducks-c** [comment]
Sorry about that but I will be unable to help regarding that. OCLP support anywhere for hackintoshes is almost nowhere to be found. 

I am unable to recreate this condition on my side no matter what I do. Different versions of macOS, reinstalls, resets, etc... I am not able to recreate this situation.

As far as I can tell, this _**might**_ be a SMBIOS issue. Try regenerating new info and trying again. 

Again, I apologize that I don't have a proper answer to this.

**Comment by Bable10** [comment]
ok thanks i will try, i am a newbie so i will ask for every problem

**Comment by Bable10** [comment]
so, I didn't ask anything because I was occupied with school, but I did some researches and i found out why the acceleretion isn't working: I have a different cpu and igpu and I know that opguide say that haswell igpu can work only until ventura but in a ocpl releas there was written your igpu is supported even with sequoia while mine only with ventura (i have the intel hd graphics 4400)

**Comment by Bable10** [comment]
but i found a tool that can make mac os think that it has another cpu/igpu, it's called hakintool, if you know how to use it can you help me (sorry for english)

**Comment by Bable10** [comment]
and is it normal that when there is no acceleration the pc is slow and it lags so much?

**Comment by Bable10** [comment]
can you answer please?
