### ISSUE TITLE
Wi-fi doesn't work in the installer

### ISSUE THREAD

**Issue by Bable10** [Krissh-C/X1C2-macOS#12]
I also tried to change the Airportitwlm.kext to a more recent version (sorry for bad english it's not my first language)

**Comment by Krissh-C** [comment]
Could you please tell me what version of macOS you are trying to install? Currently Sonoma 14.7.1 is the last update this EFI is known to work with at the moment.

Also there's 2 kexts in the EFI for different use cases and only one needs to be enabled for WiFi to work. Could you please check if both have been enabled by accident (itlwm & airportitlwm).

Airportitlwm is the one you should be using.

**Comment by Bable10** [comment]
I was trying to install macOS Sonoma 14.4 and disabled itlwm but it wasn't work so I checked Dortania's guide and I saw that airportitlwm needs AppleSecureBoot so I enable it but didn't work, also itlwm cannot funcion in the installer.

I apologize for my bad english and thank You

**Comment by Krissh-C** [comment]
Itlwm requires a separate app to work and so, cannot be used in the installer. Secure boot is not a requirement as it works without it too, hence why it is disabled.

Have you made sure you're using MacBookPro15,2 as your SMBIOS? That specific model is required for the USB Map to work which might be interfering with WiFi not showing in the installer.

I can't seem to recreate your problem on my side. Make sure you haven't made any changes to the EFI besides SMBIOS info in the config.plist

**Comment by Krissh-C** [comment]
You can dualboot but that shouldn't have any effect on wifi functionally in macOS. 

As a last resort, I'd suggest using an older version of macOS first (eg. Ventura) and replacing the wifi kext with the OS compatible one. Everything else should work just fine as long as you are still using the 15,2 SMBIOS.

After installation, you could try updating to Sonoma and replacing the wifi kext after.

Sorry I couldn't help you fix this issue but if you need any help, I will leave this issue open for a little while.

**Comment by Bable10** [comment]
I solved the wifi problem, but now after installation I click on the installer but it after loading for like 20 seconds it reboots to opencore's picker
