### ISSUE TITLE
PC goes in a reboot loop before continue the installation

### ISSUE THREAD

**Issue by Bable10** [Krissh-C/X1C2-macOS#13]
I it's always me, when it finish the installation, it reboots to the picker and i click on the installer, but after loading for 20-30 seconds it reboots to picker (I am trying macOS Sonoma 14.6.2)

**Comment by Krissh-C** [comment]
Could you please enable verbose mode by adding "-v" to your boot-args and tell me where it reboots at?

**Comment by Bable10** [comment]
It's not rebooting anymore but it is stuck on:

Loaded kexts:
(none)

**In Memory Panic Stackshot Succeeded ** Bytes Traced 1986 (Uncompressed 5008) **
MACH Reboot

**Comment by Bable10** [comment]
I think that the problem is airportitwlm because i change it with the version that i downloaded and now works but i need to see if it reboots to the picker

**Comment by Bable10** [comment]
ok i am in the configuration page it works i just change airportitwlm

i am so sorry for wasting your time
